model:
  family: gpt2
  n_dims: 20
  n_embd: 128
  n_head: 4
  n_layer: 6
  n_positions: 101
training:
  batch_size: 256
  data: markov
  data_kwargs:
    noise_std: 1.0
    initial_std: 0.0
    markov_mode: stationary
    markov_scale: 0.6
    max_seq_length: 40
    seed: 0
  task: markov_noisy_linear_regression
  task_kwargs:
    noise_std: 0.1
    y_noise: 0.1
    seed: 0
  keep_every_steps: 1000
  save_every_steps: 500
  train_steps: 500001
  resume_id: null
  curriculum:
    dims:
      start: 20
      end: 20
      inc: 0
      interval: 1000000
    points:
      start: 40
      end: 40
      inc: 0
      interval: 1000000
out_dir: D:\MyBK\Scientific_Research\Benign Overfitting in ICL\in-context-learning\models\markov_benign_overfitting\exp4_sigma_y_0p1
wandb:
  entity: hai-trinh220970-ho-chi-minh-city-university-of-technology
  project: in-context-training
  name: Markov sigma_y=0.1
  notes: Markov exp 4 label-noise sweep, sigma_y=0.1
  log_every_steps: 100
