inherit:
  - benign_harmful_dynamics.yaml
  - models/small.yaml
  - wandb.yaml

model:
  family: gpt2
  n_dims: 20
  n_embd: 128
  n_head: 4
  n_layer: 6
  n_positions: 101

training:
  batch_size: 32
  data: gaussian
  data_kwargs: {}
  task: noisy_linear_regression
  task_kwargs:
    noise_type: normal
    noise_std: 0.0
    w_distribution: gaussian
    w_kwargs:
      scale: 1.0
  keep_every_steps: 5000
  save_every_steps: 500
  train_steps: 100001
  resume_id: null

out_dir: D:\Henry-Projects\ChestXray\data\in-context-learning\models\benign_harmful_dynamics_small

wandb:
  entity: hai-trinh220970-ho-chi-minh-city-university-of-technology
  project: in-context-training
  name: benign-harmful-dynamics-small
  notes: Train small model on ID and evaluate train/test loss dynamics across OOD noise scales.
  log_every_steps: 100
