inherit: 
    - base.yaml

model:
    n_dims: 20
    n_positions: 101

training:
    task: transfer_tradeoff_task
    task_kwargs:
        prior_type: "mixture_gaussian"
        mixture_std: 2.0
        scale: 1.0
    data: gaussian
    data_kwargs: {}
    curriculum:
        dims:
            start: 5
            end: 20
            inc: 1
            interval: 2000
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
    batch_size: 64
    learning_rate: 0.0001
    train_steps: 50001

out_dir: ../models/transfer_tradeoff_task

wandb:
    project: "in-context-training"
    entity: "hai-trinh220970-ho-chi-minh-city-university-of-technology"
    name: "case5_transfer_tradeoff"
    notes: "Case 5: Transfer Tradeoff - p×N experiment (Wakayama) - Mixture Gaussian prior"
    log_every_steps: 100