inherit:
  - base.yaml

model:
  n_dims: 20
  n_positions: 101

training:
  task: sparse_regression_killer
  task_kwargs:
    k_sparse: 2
    scale: 1.0
  data: uniform
  data_kwargs: {}
  curriculum:
    dims:
      start: 5
      end: 20
      inc: 1
      interval: 2000
    points:
      start: 11
      end: 41
      inc: 2
      interval: 2000
  batch_size: 64
  learning_rate: 0.0001
  train_steps: 500001

out_dir: ../models/sparse_regression_killer

wandb:
    project: "in-context-training"
    entity: "hai-trinh220970-ho-chi-minh-city-university-of-technology"
    name: "case1_sparse_regression"
    notes: "Case 1: Sparse Regression - only k=2 dims non-zero - Ridge Trap"
    log_every_steps: 100