inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
  family: gpt2
  n_dims: 5
  n_embd: 128
  n_head: 8
  n_layer: 4
  n_positions: 100

training:
  batch_size: 32
  curriculum:
    dims:
      start: 5
      end: 5
      inc: 0
      interval: 1
    points:
      start: 6
      end: 6
      inc: 0
      interval: 1
  data: ar1
  keep_every_steps: 10000
  learning_rate: 0.0003
  num_tasks: null
  num_training_examples: null
  resume_id: null
  save_every_steps: 100
  task: ar1_linear_regression
  task_kwargs: {
    "compute_gradient": True
  } 
  train_steps: 501

out_dir: ../models/linear_regression

wandb:
    name: "fig3_6_points_"
