inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
  family: gpt2
  n_dims: 5
  n_embd: 128
  n_head: 8
  n_layer: 4
  n_positions: 100

training:
  batch_size: 32
  curriculum:
    dims:
      start: 5
      end: 5
      inc: 0
      interval: 1
    points:
      start: 21
      end: 21
      inc: 0
      interval: 1
  data: ar1
  keep_every_steps: 100000
  learning_rate: 0.0003
  num_tasks: null
  num_training_examples: null
  resume_id: null
  save_every_steps: 1000
  task: ar1_linear_regression
  task_kwargs: {} 
  train_steps: 50001

out_dir: ../models/linear_regression

wandb:
    name: "linear_regression_toy with 5 points"
