inherit: 
    - base.yaml

model:
    family: gpt2
    n_dims: 20
    n_embd: 128
    n_head: 8
    n_layer: 4
    n_positions: 100

training:
    task: uniform_hypersphere_regression  # Using our new task
    task_kwargs:
        scale: 1.0  # Scale factor for weights
    data: gaussian  # Using standard Gaussian inputs
    curriculum:
        dims:
            start: 20
            end: 20
            inc: 0
            interval: 2000
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
    batch_size: 32
    learning_rate: 0.0003
    train_steps: 50001

out_dir: ../models/uniform_hypersphere_regression

wandb:
    name: "uniform_hypersphere_regression"
    notes: "Training with weights uniformly distributed on unit hypersphere"